<a href="https://colab.research.google.com/github/ramyarangan/ssrp_srec_python_workshop_2021/blob/master/day5_python_room1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 5: Scope, Numpy, Command Line Python, and 
Date: June 18, 2021

Room 1

Schedule

|Session #| Time | Instructor | Helper 1 | Helper 2|
|-|-|-|-|-|
|1| 10:30-11:30 | Roshni| Rachael | Alex |
| Break 1 | 11:30-11:45 |
|2| 11:45-12:45 | Alex | Roshni | Rachael |
|Lunch Break| 12:45 - 1:30|
|3| 1:30 - 2:30| Roshni |
|Break| 2:30 - 2:45|
| Next Steps| 2:45-3:30|Ramya |

## Learning objectives
1. Learn about variable scoping
2. Explain why the numpy library is useful to work with tabular data and perform statistical analysis
3. Use the PEP-8 convention for programming style and best practices
4. Test their own code and libraries for fidelity
5. Run a python script directly from the command line
6. Know resources where they can look for the future


## Session 1

In [ ]:
eggs_per_carton = 15

def egg_counter(num_cartons): total_eggs = num_cartons * eggs_per_carton return(total_eggs)

egg_counter(3)

print(num_cartons) #you never assigned num_cartons to anything --> num_cartons undefined
print(total_eggs) #total_eggs not defined outside the function

In [ ]:
eggs_per_carton = 15

def egg_counter(num_cartons, eggs_per_carton): 
  total_eggs = num_cartons * eggs_per_carton
  return(total_eggs)

egg_counter(3, 10) # 30 --> priority to what is defined inside the function
print(eggs_per_carton)

15


In [ ]:
eggs_per_carton = 15

def egg_counter(num_cartons, eggs_per_cartons): 
  total_eggs = num_cartons * eggs_per_carton
  return(total_eggs)

egg_counter(3, 10) # 30 --> priority to what is defined inside the function
# general coding good practice : keep as few variables defined outisde of fucntions, use dedicated variable names inside functions

45

## Session 2

Numpy
numpy is a library to do maths with collections of numbers (vectors or arrays, matrices)

In [ ]:
alist = [1,5,10,12,3]
alist

[1, 5, 10, 12, 3]

In [ ]:
alist_new = alist + 1

TypeError: ignored

In [ ]:
alist_new = alist.append(1) # inplace operation , modifies the list you use

In [ ]:
alist

[1, 5, 10, 12, 3, 1]

In [ ]:
# no direct way to do + 1 in a list
# we could write a for loop
alist_new = []
for value in alist:
  alist_new.append(value + 1)
print(alist_new)


[2, 6, 11, 13, 4, 2]


In [ ]:
alist**2+(alist-1)+cos(alist)

In [ ]:
import numpy as np

In [ ]:

alist

[1, 5, 10, 12, 3, 1]

In [ ]:
# create numpy array
x = np.array(alist)
print(x)

[ 1  5 10 12  3  1]


In [ ]:
x + 1 # math friendly

array([ 2,  6, 11, 13,  4,  2])

In [ ]:
# y=x^2 + 2x
y=x**2 + 2*x
y

array([  3,  35, 120, 168,  15,   3])

In [ ]:
type(alist)

list

In [ ]:
type(x) #numpy.ndarray is the core data structure in numpy

numpy.ndarray

In [ ]:
x.shape

(6,)

In [ ]:
# make a two dimensional array
M = [[1, 3, 5],[-1, 10, 6]]


In [ ]:
type(M)

list

In [ ]:
# convert M to a numpy 2d array
M_array=np.array(M)
M_array

array([[ 1,  3,  5],
       [-1, 10,  6]])

In [ ]:
type(M_array)

numpy.ndarray

In [ ]:
M_array.shape

(2, 3)

In [ ]:
M2=np.array([[1,2,3],[4,5,8],[0,0,0]])
M2

array([[1, 2, 3],
       [4, 5, 8],
       [0, 0, 0]])

Slicing

In [ ]:
# get the 2 row of this matrix M2
M2[1, :] # M[row_pos, col_pos]

array([4, 5, 8])

In [ ]:
# first 2 rows, columns 2 and 3
M2[0:2,[1,2]]
M2[0:2, 1:3]

array([[2, 3],
       [5, 8]])

In [ ]:
# numpy array to pandas dataframe
import pandas as pd
# rcall earlier we loaded data from external file : pd.read_csv(filename)
# here we make the df from scratch
df=pd.DataFrame(M2)
df

0  1  2
0  1  2  3
1  4  5  8
2  0  0  0

In [ ]:

# we want to give names to the rows and columns
# rows are days : day0, day1, day2
# columns are cities : seattle, denver, ny
df=pd.DataFrame(M2,index=['day0','day1','day2'], columns=['seattle','denver','ny'])
df

seattle  denver  ny
day0        1       2   3
day1        4       5   8
day2        0       0   0

In [ ]:
#make the same dataframe but multiply all elements by 10
df=pd.DataFrame(M2**2+np.cos(M2),index=['day0','day1','day2'], columns=['seattle','denver','ny'])
df

seattle     denver         ny
day0   1.540302   3.583853   8.010008
day1  15.346356  25.283662  63.854500
day2   1.000000   1.000000   1.000000

In [ ]:
# math function with numpy us the math functions in the numpy library, rather than in the math library
import math
math.cos(1)
#math.cos(M2) # cosine of all entries in the matrix --> math library NO GOOD for arrays
np.cos(M2)


array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219, -0.14550003],
       [ 1.        ,  1.        ,  1.        ]])

GO from pandas to numpy

In [ ]:
df

seattle     denver         ny
day0   1.540302   3.583853   8.010008
day1  15.346356  25.283662  63.854500
day2   1.000000   1.000000   1.000000

In [ ]:
# get all the numbers squared
# pull these numbers into a numpy array
M3 = df.values #pandas INTERNALLY uses numpy arrays to store the data
M3

array([[ 1.54030231,  3.58385316,  8.0100075 ],
       [15.34635638, 25.28366219, 63.85449997],
       [ 1.        ,  1.        ,  1.        ]])

In [ ]:
# modify an entry in the array
# say I want row1, column1 = 0
M3[0, 0]=0
M3

array([[ 0.        ,  3.58385316,  8.0100075 ],
       [15.34635638, 25.28366219, 63.85449997],
       [ 1.        ,  1.        ,  1.        ]])

In [ ]:
df  # df.values delves into the datset underlying the df 
#--> if we modify this dataset, we're implicitely modifying the dataframe

seattle     denver         ny
day0   0.000000   3.583853   8.010008
day1  15.346356  25.283662  63.854500
day2   1.000000   1.000000   1.000000

In [ ]:
#create a new aray that has a copy of the pandas dataframe values
M3_copy=df.values.copy()
M3_copy

array([[ 0.        ,  3.58385316,  8.0100075 ],
       [15.34635638, 25.28366219, 63.85449997],
       [ 1.        ,  1.        ,  1.        ]])

In [ ]:
M3_copy[0,0]=100
M3_copy

array([[100.        ,   3.58385316,   8.0100075 ],
       [ 15.34635638,  25.28366219,  63.85449997],
       [  1.        ,   1.        ,   1.        ]])

In [ ]:
df

seattle     denver         ny
day0   0.000000   3.583853   8.010008
day1  15.346356  25.283662  63.854500
day2   1.000000   1.000000   1.000000

## Session 3

## Widgets!!

In [11]:
from ipywidgets import interact
import ipywidgets as widgets

In [14]:
def my_func(x):
  print(f"The square of {x} is {x**2}")

In [15]:
_=interact(my_func, x=10)

interactive(children=(IntSlider(value=10, description='x', max=30, min=-10), Output()), _dom_classes=('widget-…

In [16]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
def my_func(x):
  return x**2

def my_plot_func(function_type):
  x = np.arange(-10, 10, 0.1)
  plt.plot(x, function_type(x))

In [22]:
_=interact(my_plot_func, function_type=[np.cos, np.sin, np.log10, my_func])

interactive(children=(Dropdown(description='function_type', options=(<ufunc 'cos'>, <ufunc 'sin'>, <ufunc 'log…

In [23]:
x = "hello world"
print(f"This is the content of x {x}")

This is the content of x hello world


In [25]:
"this " + " that" + "the other" + x

'this  thatthe otherhello world'